language: node_js
nvm:

matrix:
  include:
  - node_js: "12"
    script: npm run test-with-temp-cloud
  - node_js: "14"
    script: npm run test-with-temp-cloud
  - node_js: "16"
    script: npm run test-with-temp-cloud

notifications:
  email:
    recipients:
      - sdk_developers@cloudinary.com
